blog/urls.py
"""Blog app URL Configuration."""

from django.urls import path
from django.views.generic.base import RedirectView

from blog import views

app_name = "blog"

urlpatterns = [
    path("articles/", views.IndexListView.as_view(), name="index"),
    path("", RedirectView.as_view(pattern_name="blog:index", permanent=False)),
    path("feed/", views.PersonalNewsFeedView.as_view(), name="feed"),
    path("articles/<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("articles/new/", views.ArticleCreateView.as_view(), name="new_article"),
    path("articles/<int:pk>/edit/", views.ArticleUpdateView.as_view(), name="update_article"),
    path("articles/<int:pk>/delete/", views.ArticleDestroyView.as_view(), name="destroy_article",),
    path("blogs/", views.BlogListView.as_view(), name="blogs"),
    path("blogs/<int:pk>/", views.BlogDetailView.as_view(), name="articles_by_blog"),
    path("blogs/new", views.BlogCreateView.as_view(), name="new_blog"),
    path("languages/new", views.LanguageCreateView.as_view(), name="new_language"),
    path("bookmarks/", views.BookmarksView.as_view(), name="bookmarks"),
    path("bookmarks/add", views.AddArticleInBookmarks.as_view(), name="add_article_to_bookmarks"),
    path("bookmarks/delete", views.RemoveArticleFromBookmarks.as_view(), name="remove_article_from_bookmarks"),
]

config/urls.py
"""
Django-blog URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Администрирование Incognito"
admin.site.index_title = "Администрирование вашего сайта"
admin.site.site_title = "Административный сайт Incognito"


urlpatterns = [
    path("", include("blog.urls")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path("select2/", include("django_select2.urls")),
]

urlpatterns += [
    # 'неявные' view из auth app (шаблоны лежат в /templates/registration)
    path("users/", include("django.contrib.auth.urls")),
    # остальные view и шаблоны пользователей лежат в users app
    path("users/", include("users.urls")),
]

urlpatterns += [
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
    path('__debug__/', include('debug_toolbar.urls')),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
"""Users app URL Configuration."""

from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.UserListView.as_view(), name="users"),
    path("register/", views.SiqnUp.as_view(), name="signup"),
    path("<username>", views.ProfileDetailView.as_view(), name="profile"),
    path("<username>/edit", views.UserUpdateView.as_view(), name="update_user"),
    path("<username>/delete", views.UserDestroyView.as_view(), name="destroy_user"),
    path("following/", views.UserFollowingListView.as_view(), name="following"),
    path("add_author/", views.AddAuthorToProfileView.as_view(), name="add_author_to_profile"),
    path("remove_author/", views.RemoveAuthorFromProfileView.as_view(), name="remove_author_from_profile"),
    path("add_blog/", views.AddBlogToProfileView.as_view(), name="add_blog_to_profile"),
    path("remove_blog/", views.RemoveBlogFromProfileView.as_view(), name="remove_blog_from_profile"),
]

blog/models.py
import datetime

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from sorl import thumbnail
from tinymce.models import HTMLField


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField("Создано", auto_now_add=True)
    updated_at = models.DateTimeField("Обновлено", auto_now=True)

    class Meta:
        abstract = True


class Blog(TimeStampedModel):
    name = models.CharField("Название", max_length=30, unique=True)
    description = models.CharField("Описание", max_length=60)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:articles_by_blog", kwargs={"pk": self.pk})


class Language(models.Model):
    language = models.CharField("Язык", max_length=16, unique=True)

    def __str__(self):
        return self.language


def get_user_directory_path(instance, filename):
    return f"users/user_{instance.author.id}/article_{instance.id}/{filename}"


class Article(TimeStampedModel):
    "Article of blog."
    title = models.CharField("Заголовок", max_length=100, unique=True)
    title_photo = thumbnail.ImageField(
        "Фото", upload_to=get_user_directory_path, blank=True, null=True
    )
    description = models.CharField("Описание", max_length=100)
    body = HTMLField("Содержание")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="Автор", on_delete=models.CASCADE
    )
    language = models.ForeignKey(
        Language, verbose_name="Язык", blank=True, null=True, on_delete=models.SET_NULL
    )
    blogs = models.ManyToManyField(Blog, verbose_name="Блоги", blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:article_detail", kwargs={"pk": self.pk})

    def was_updated_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.updated_at

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django_select2 import forms as s2forms

from blog.models import Article


class LanguageWidget(s2forms.ModelSelect2Widget):
    search_fields = ["language__icontains"]


class BlogsWidget(s2forms.ModelSelect2MultipleWidget):
    search_fields = [
        "name__icontains",
        "description__icontains",
    ]


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "description", "title_photo", "body", "language", "blogs"]
        widgets = {
            "language": LanguageWidget,
            "blogs": BlogsWidget,
        }

    def clean_title_photo(self):
        title_photo = self.cleaned_data.get("title_photo")

        if title_photo:
            width, height = get_image_dimensions(title_photo)
            if (width < 619) or (height < 349):
                raise ValidationError(
                    """
                    Слишком маленькое изображение,
                    минимальная высота и ширина - 619 и 349 пикселей.
                    """
                )
            elif (width > 1980) or (height > 1080):
                raise ValidationError(
                    """Слишком большое изображение,
                    максимальная высота и ширина - 1980 и 1080 пикселей.
                    """
                )
        return title_photo

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.db.transaction import atomic
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import BaseDeleteView, CreateView, UpdateView

from blog import filters, models
from blog.forms import ArticleForm
from blog.services import (
    add_article_to_bookmarks,
    get_articles_for_cards,
    get_articles_for_search_query,
    get_blogs_with_counters,
    get_personal_news_feed,
    is_author_of_article,
    remove_article_from_bookmarks,
)


class IndexListView(ListView):
    """Returns the list of articles to the main page"""

    model = models.Article
    template_name = "blog/index.html"
    paginate_by = 6

    def get_queryset(self):
        self.search_query = self.request.GET.get("search_query")
        func = (
            get_articles_for_search_query(self.search_query)
            if self.search_query
            else get_articles_for_cards()
        )

        self.filter = filters.ArticleFilter(
            self.request.GET,
            queryset=func,
            request=self.request,
        )
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter
        if self.search_query:
            context["query"] = self.search_query
        return context


class PersonalNewsFeedView(LoginRequiredMixin, ListView):
    """Returns personal news feed for current logged-in user."""

    model = models.Article
    template_name = "blog/user_news_feed.html"
    paginate_by = 6

    def get_queryset(self):
        return get_personal_news_feed(self.request.user)


class ArticleDetailView(DetailView):
    """Returns the details of article."""

    model = models.Article


@method_decorator(decorator=atomic, name="dispatch")
class ArticleCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Returns a form for creation an article by GET request
    or creates an new article by POST request.
    """

    permission_required = "blog.add_article"

    model = models.Article
    form_class = ArticleForm
    template_name = "blog/new_article.html"

    success_message = "Статья успешно создана!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


@method_decorator(decorator=atomic, name="dispatch")
class ArticleUpdateView(
    UserPassesTestMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView
):
    """
    Returns a form for updating an article by GET request
    or updates an article by POST request.
    """

    permission_required = "blog.change_article"

    model = models.Article
    form_class = ArticleForm
    template_name = "blog/update_article.html"

    success_message = "Статья успешно обновлена"

    def test_func(self):
        return is_author_of_article(
            author=self.request.user, article_id=self.kwargs.get("pk")
        )


@method_decorator(decorator=atomic, name="dispatch")
class ArticleDestroyView(
    UserPassesTestMixin, PermissionRequiredMixin, SuccessMessageMixin, BaseDeleteView
):
    """Deletes the article from database."""

    permission_required = "blog.delete_article"

    model = models.Article
    success_url = reverse_lazy("blog:index")

    success_message = "Статья успешно удалена"

    def test_func(self):
        return is_author_of_article(
            author=self.request.user, article_id=self.kwargs.get("pk")
        )


@method_decorator(decorator=atomic, name="dispatch")
class BlogCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """Creates a new blog."""

    model = models.Blog
    fields = ["name", "description"]
    template_name_suffix = "_create_form"
    success_message = "Новый блог успешно создан."


class BlogListView(ListView):
    """Returns the list of blogs."""

    model = models.Blog
    paginate_by = 5

    def get_queryset(self):
        self.filter = filters.BlogFilter(
            self.request.GET,
            queryset=get_blogs_with_counters(),
            request=self.request,
        )
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter
        return context


class BlogDetailView(SingleObjectMixin, ListView):
    """Retruns the details of blog and the list of articles its blog."""

    template_name = "blog/articles_by_blog.html"
    context_object_name = "blog"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=models.Blog.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.article_set.all()


@method_decorator(decorator=atomic, name="dispatch")
class LanguageCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """Creates a new language."""

    model = models.Language
    fields = ["language"]
    template_name_suffix = "_create_form"
    success_message = "Новый язык успешно создан."
    success_url = reverse_lazy("blog:new_language")


class BookmarksView(LoginRequiredMixin, ListView):
    model = models.Article
    template_name = "blog/bookmarks.html"
    paginate_by = 6

    def get_queryset(self):
        self.filter = filters.BookmarkFilter(
            self.request.GET,
            queryset=self.request.user.bookmarks.all().defer("language_id", "body"),
            request=self.request,
        )
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter
        return context


@method_decorator(decorator=atomic, name="dispatch")
class AddArticleInBookmarks(LoginRequiredMixin, View):
    """
    Add article to the bookmarks user.
    """

    def post(self, request, *args, **kwargs):
        article_id = request.POST.get("article_id")
        add_article_to_bookmarks(request.user, article_id)
        messages.success(request, "Публикация добавлена в закладки.")
        return redirect("blog:article_detail", pk=article_id)


@method_decorator(decorator=atomic, name="dispatch")
class RemoveArticleFromBookmarks(LoginRequiredMixin, View):
    """
    Remove article from the bookmarks user.
    """

    def post(self, request, *args, **kwargs):
        article_id = request.POST.get("article_id")
        remove_article_from_bookmarks(request.user, article_id)
        messages.success(request, "Публикация убрана из закладок.")
        return redirect("blog:article_detail", pk=article_id)

blog/templates/blog/article_detail.html
{% extends "base.html" %}

{% block title %}{{ article.title}} | {{ article.author.get_username }}{% endblock %}

{% block content %}
<h2 class="display-4">{{ article.title }}</h1>
  {% if user.get_username == article.author.get_username and perms.blog.change_article %}
  <a href="{% url 'blog:update_article' article.id %}" class="btn btn-outline-secondary mb-2 btn-sm">Редактировать</a>
  {% endif %}


  {% if user.is_authenticated %}
    {% if article in user.bookmarks.all %}
    <form action="{% url 'blog:remove_article_from_bookmarks' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="article_id" value="{{ article.id }}">
      <button class="btn btn-outline-secondary mb-2 btn-sm">Убрать из закладок</button>
    </form>
    {% else %}
    <form action="{% url 'blog:add_article_to_bookmarks' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="article_id" value="{{ article.id }}">
      <button class="btn btn-outline-secondary mb-2 btn-sm">Добавить в закладки</button>
    </form>
    {% endif %}
  {% endif %}


  <div class="m-3">

    {% load thumbnail %}
    {% thumbnail article.author.profile_picture "75x75" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-fluid img-thumbnail rounded-pill"
      alt="profile-picture">
    {% empty %}
    {% load static %}
    <img src="{% static 'users/images/default.jpg' %}" width="75" height="75"
      class="img-fluid img-thumbnail rounded-pill" alt="profile-picture">
    {% endthumbnail %}

    <b><a href="{% url 'users:profile' article.author.get_username %}">{{ article.author.get_username }}</a></b>
  </div>

  {% if article.title_photo %}
  <img src="{{ article.title_photo.url }}" class="img-fluid rounded mx-auto d-block" alt="title-photo">
  {% endif %}

  {% include "blog/includes/blogs_snippet.html" with blogs=article.blogs.all only %}

  {% if article.language %}
  <p><b>Язык: </b>{{ article.language }}</p>
  {% endif %}
  <p><b>Описание: </b>{{ article.description }}</p>
  <p>{{ article.body|safe }}</p>
  {% endblock %}

blog/templates/blog/articles_by_blog.html
{% extends "base.html" %}

{% block title %}Блоги | {{ blog.name }}{% endblock %}

{% block content %}
<h2 class="display-4">Статьи в блоге<div>{{ blog.name }}</div></h2>
<small>Создан {{ blog.created_at|date:"j E" }}</small>
<p>{{ blog.description }}</p>

{% if user.is_authenticated %}
  {% if blog in user.blogs.all %}
  <form action="{% url 'users:remove_blog_from_profile' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="blog_id" value="{{ blog.id }}">
    <input type="hidden" name="blog_name" value="{{ blog.name }}">
    <button class="btn btn-outline-secondary mb-2">Отписаться</button>
  </form>
  {% else %}
  <form action="{% url 'users:add_blog_to_profile' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="blog_id" value="{{ blog.id }}">
    <input type="hidden" name="blog_name" value="{{ blog.name }}">
    <button class="btn btn-outline-secondary mb-2">Подписаться</button>
  </form>
  {% endif %}
{% endif %}

{% include "blog/includes/articles_snippet.html" %}
{% endblock %}

blog/templates/blog/articles_by_tag.html
{% extends "base.html" %}

{% block title %}Теги | {{ tag.name }}{% endblock %}

{% block content %}
    <section>
        <h2 class="display-4">Статьи по тегу <div>{{ tag.name }}</div></h2>

        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for article in articles %}
            <div class="col">
                <article class="card h-100">
                    <img src="https://img2.fonwall.ru/o/tk/alpine-fields-landscape.jpg" class="card-img-top" alt="image">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ article.created_at|date:"j E" }}</h4>
                        <p class="card-text">{{ article.body|truncatewords:10 }}</p>
                        <a href="{% url 'blog:article_detail' article.id %}" class="btn btn-outline-primary">Читать</a>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Обновлено 5 мин. назад</small>
                    </div>
                </article>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
    {% block style %}{% endblock %}
</head>
<body>
    <header>
        <div class="logo"'>ИНКОГНИТО<span class="end-logo">.РУ</span></div>
        <nav>
            <ul class="menu">
                <li><a href="{% url 'blog:index' %}">Главная</a></li>
                <li><a href="{% url 'blog:tags' %}">Теги</a></li>
                <li><a href="{% url 'blog:authors' %}">Авторы</a></li>
                <li><a href="{% url 'blog:new_article' %}">Создать статью</a></li>
                <li><a href="{% url 'blog:new_author' %}">Создать автора</a></li>
            </ul>
        </nav>
        <nav class="menu">
            <ul>
                <li><a href="{% url 'search:search' %}">Поиск</a></li>
                <li><a href="">Вход</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% block search %}{% endblock %}

        {% block content %}{% endblock %}

        {% block pagination %}
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="link-pagination">назад</a>
                    {% endif %}
                    <span class="page-current">
                        cтраница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="link-pagination">далее</a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
        {% endblock %}
    </main>
    <div class="clear"></div>
    <footer>
    </footer>
</body>
</html>

blog/templates/blog/base_article_list.html
{% extends "base.html" %}

{% block content %}

{% block othercontent %}{% endblock %}
{% load bootstrap5 %}

{% if filter %}
<form method="get">
  <div class="d-flex align-items-start flex-column">
    <div class="d-flex justify-content-start align-items-start">
      <div>{% bootstrap_field filter.form.range bound_css_class='form-select-sm' %}</div>
    </div>
    <div class="ms-2 mb-3"><input type="submit" class="btn btn-outline-primary" value="Найти"></div>
  </div>
</form>
{% endif %}


<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
  {% for article in object_list %}
  <div class="col">
    <article class="card h-100">

      {% load thumbnail %}
      {% thumbnail article.title_photo "619x349" crop="center" as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top h-100"
        alt="title-photo">
      {% empty %}
      {% load static %}
      <img src="{% static 'blog/placeholder/default.jpeg' %}" width="619" height="349" class="card-img-top h-100"
        alt="title-photo">
      {% endthumbnail %}

      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ article.created_at|date:"j E" }}</h4>
          <p class="card-text text-truncate">{{ article.description|truncatewords:10 }}</p>
          <a href="{% url 'blog:article_detail' article.id %}" class="btn btn-outline-primary">Читать</a>
      </div>
      <div class="card-footer">
        {% load humanize %}
        <small class="text-muted">
          {% if article.was_updated_recently %}
          Обновлено {{ article.updated_at|naturaltime }}
          {% else %}
          Обновлено {{ article.updated_at|date }}
          {% endif %}
        </small>
      </div>
    </article>
  </div>
  {% empty %}
  <p>Еще ничего не опубликовано</p>
  {% endfor %}
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block title %}Блоги{% endblock %}

{% load bootstrap5 %}

{% block content %}
<div>
  <h2 class="display-4">Блоги</h2>

  {% if user.is_authenticated %}
  <a href="{% url 'blog:new_blog' %}" target="_blank" class="btn btn-outline-secondary mt-2 mb-3">
    Создать блог
  </a>
  {% endif %}

  <form method="get">
    <div class="d-flex align-items-start flex-column">
      <div class="d-flex justify-content-start align-items-center">
        <div>{% bootstrap_field filter.form.name bound_css_class='' %}</div>
        <div class="mt-3 ms-2"><input type="submit" class="btn btn-outline-primary" value="Найти"></div>
      </div>
      <div class="d-flex justify-content-start align-items-start">
        <div>{% bootstrap_field filter.form.by_followers_count bound_css_class='form-select-sm' %}</div>
        <div class="ms-2">{% bootstrap_field filter.form.by_article_count bound_css_class='form-select-sm' %}</div>
      </div>
    </div>
  </form>


  <ul class="list-group list-group-flush">
    <li class="list-group-item d-flex justify-content-end align-items-start">
      <div>Подписчиков</div>
      <div class="ms-4">Публикаций</div>
    </li>
    {% for blog in blog_list %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 mt-1 me-auto text-break">
        <a href="{% url 'blog:articles_by_blog' blog.pk %}">
          <div class="fw-bold text-break">{{ blog.name }}</div>
        </a>
        {{ blog.description }}
      </div>
      <span class="badge bg-secondary rounded-pill ms-5 me-5">{{ blog.user__count }}</span>
      <span class="badge bg-secondary rounded-pill ms-5">{{ blog.article__count }}</span>
    </li>
    {% empty %}
    <p class="mt-3">Пока ничего нет</p>
    {% endfor %}
  </ul>
</div>
{% endblock %}

blog/templates/blog/new_article.html
{% extends "base.html" %}

{% block title %}Новая статья | {{ user.get_username }}{% endblock %}

{% block style %}
{{ form.media.css }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <h2 class="display-4">Создание новой статьи</h1>

      <div class="d-flex justify-content-end mb-2">
        {% if user.is_authenticated %}
        <a href="{% url 'blog:new_language' %}" target="_blank" class="btn btn-outline-primary btn-sm me-2">
          Новый язык
        </a>
        <a href="{% url 'blog:new_blog' %}" target="_blank" class="btn btn-outline-primary btn-sm">
          Новый блог
        </a>
      </div>

      <form action="{% url 'blog:new_article' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load bootstrap5 %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary" onclick="this.form.submit(); this.disabled = true;">
          Опубликовать
        </button>
      </form>
      {% endif %}
  </div>
</div>
{% endblock %}

blog/templates/blog/update_article.html
{% extends "base.html" %}

{% block title %}Редактирование статьи | {{ article.author.get_username }}{% endblock %}

{% block style %}
{{ form.media.css }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
{% endblock %}

{% block content %}
<h2 class="display-4">Редактирование статьи</h4>

  <div class="d-flex justify-content-end mb-2">
    {% if user.is_authenticated %}
    <a href="{% url 'blog:new_language' %}" target="_blank" class="btn btn-outline-primary btn-sm me-2">
      Новый язык
    </a>
    <a href="{% url 'blog:new_blog' %}" target="_blank" class="btn btn-outline-primary btn-sm">
      Новый блог
    </a>
    {% endif %}
  </div>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% load bootstrap5 %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" onclick="this.form.submit(); this.disabled = true;">
      Сохранить
    </button>
    {% endbuttons %}
  </form>

    <!-- Кнопка-триггер модального окна -->
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Удалить
    </button>

  <!-- Модальное окно для удаления -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="RemoveModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Удаление</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>
        <div class="modal-body">
          Вы уверены что хотите удалить статью?
          Статья будет удалена навсегда.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>

          <form action="{% url 'blog:destroy_article' article.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="this.form.submit(); this.disabled = true;">
              Удалить
            </button>
          </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/user_news_feed.html
{% extends "base.html" %}

{% block content %}
<h2 class="display-4">Ваша личная лента</h2>

<a href="{% url 'users:following' %}" class="btn btn-outline-primary mb-3">Посмотреть подписки</a>

<div class="mb-5">
  {% include "blog/includes/blogs_snippet.html" with blogs=user.blogs.all only %}
</div>

{% include "blog/includes/articles_snippet.html" %}
{% endblock %}