blog/urls.py
"""Blog app URL Configuration."""

from django.urls import path
from django.views.generic.base import RedirectView

from blog import views

app_name = "blog"

urlpatterns = [
    path("articles/", views.IndexListView.as_view(), name="index"),
    path("", RedirectView.as_view(pattern_name="blog:index", permanent=False)),
    path("feed/", views.PersonalNewsFeedView.as_view(), name="feed"),
    path("articles/<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("articles/new/", views.ArticleCreateView.as_view(), name="new_article"),
    path("articles/<int:pk>/edit/", views.ArticleUpdateView.as_view(), name="update_article"),
    path("articles/<int:pk>/delete/", views.ArticleDestroyView.as_view(), name="destroy_article",),
    path("blogs/", views.BlogListView.as_view(), name="blogs"),
    path("blogs/<int:pk>/", views.BlogDetailView.as_view(), name="articles_by_blog"),
    path("blogs/new", views.BlogCreateView.as_view(), name="new_blog"),
    path("languages/new", views.LanguageCreateView.as_view(), name="new_language"),
    path("bookmarks/", views.BookmarksView.as_view(), name="bookmarks"),
    path("bookmarks/add", views.AddArticleInBookmarks.as_view(), name="add_article_to_bookmarks"),
    path("bookmarks/delete", views.RemoveArticleFromBookmarks.as_view(), name="remove_article_from_bookmarks"),
]

config/urls.py
"""
Django-blog URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Администрирование Incognito"
admin.site.index_title = "Администрирование вашего сайта"
admin.site.site_title = "Административный сайт Incognito"


urlpatterns = [
    path("", include("blog.urls")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path("select2/", include("django_select2.urls")),
]

urlpatterns += [
    # 'неявные' view из auth app (шаблоны лежат в /templates/registration)
    path("users/", include("django.contrib.auth.urls")),
    # остальные view и шаблоны пользователей лежат в users app
    path("users/", include("users.urls")),
]

urlpatterns += [
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
    path('__debug__/', include('debug_toolbar.urls')),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
"""Users app URL Configuration."""

from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.UserListView.as_view(), name="users"),
    path("register/", views.SiqnUp.as_view(), name="signup"),
    path("<username>", views.ProfileDetailView.as_view(), name="profile"),
    path("<username>/edit", views.UserUpdateView.as_view(), name="update_user"),
    path("<username>/delete", views.UserDestroyView.as_view(), name="destroy_user"),
    path("following/", views.UserFollowingListView.as_view(), name="following"),
    path("add_author/", views.AddAuthorToProfileView.as_view(), name="add_author_to_profile"),
    path("remove_author/", views.RemoveAuthorFromProfileView.as_view(), name="remove_author_from_profile"),
    path("add_blog/", views.AddBlogToProfileView.as_view(), name="add_blog_to_profile"),
    path("remove_blog/", views.RemoveBlogFromProfileView.as_view(), name="remove_blog_from_profile"),
]

users/models.py
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.cache import cache
from django.db import models
from django.urls import reverse
from django.utils import timezone
from sorl import thumbnail

from blog.models import Article, Blog


def get_user_directory_path(instance, filename):
    return f"users/user_{instance.id}/profile_picture/{filename}"


class User(AbstractUser):
    """A user model."""

    username = models.CharField(
        "Имя пользователя",
        help_text="""
        Обязательное поле. Не более 10 символов.
        только буквы, цифры и символы @/./+/-/_.
        """,
        unique=True,
        max_length=10,
    )
    email = models.EmailField(
        "Электронный адрес",
        help_text="Почта должна быть уникальной.",
        error_messages={"unique": "Электронная почта уже используется."},
        unique=True,
    )
    profile_picture = thumbnail.ImageField(
        "Фото пользователя", upload_to=get_user_directory_path, blank=True, null=True
    )
    about_me = models.CharField("О себе", max_length=60, blank=True, null=True)
    blogs = models.ManyToManyField(
        Blog, verbose_name="Следит за данными блогами", blank=True
    )
    following = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="followers",
        verbose_name="Следит за данными авторами",
        blank=True,
    )
    bookmarks = models.ManyToManyField(
        Article, verbose_name="Закладки", through="BookmarksRelation"
    )

    def __str__(self):
        return self.get_username()

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"username": self.username})

    def last_seen(self):
        return cache.get(f"last_seen_{self.id}")

    def is_online(self):
        last_seen = self.last_seen()
        if last_seen:
            now = timezone.now()
            if now > last_seen + timedelta(seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            return True
        return False


class BookmarksRelation(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_added = models.DateTimeField()

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django_select2 import forms as s2forms

from blog.forms import BlogsWidget

from .models import User


class AuthorsWidget(s2forms.ModelSelect2MultipleWidget):
    search_fields = [
        "username__icontains",
        "first_name__icontains",
        "last_name__icontains",
    ]


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "profile_picture",
            "about_me",
            "blogs",
            "following",
        ]
        widgets = {
            "blogs": BlogsWidget,
            "following": AuthorsWidget,
        }

    def clean_profile_picture(self):
        picture = self.cleaned_data.get("profile_picture", False)
        if picture:
            width, height = get_image_dimensions(picture)
            if (width < 150) or (height < 150):
                raise ValidationError(
                    """
                    Слишком маленькое изображение,
                    минимальная высота и ширина - 150 пикселей.
                    """
                )
            elif (width > 1980) or (height > 1080):
                raise ValidationError(
                    """
                    Слишком большое изображение,
                    максимальная высота и ширина - 1980 и 1080 пикселей.
                    """
                )
        return picture

users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.db.transaction import atomic
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import BaseDeleteView

from users.filters import UserFilter
from users.forms import CustomUserChangeForm, SignUpForm
from users.services import (
    add_authors_to_user,
    add_blogs_to_user,
    add_user_to_base_group_or_create_one,
    get_user_following_list,
    get_users_with_all_counter,
    get_users_with_counters,
    remove_authors_from_user,
    remove_blogs_from_user,
)


@method_decorator(decorator=atomic, name="dispatch")
class SiqnUp(CreateView):
    """Registers the user on the site."""

    model = get_user_model()
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = settings.LOGIN_REDIRECT_URL

    def form_valid(self, form):
        user = form.save()
        add_user_to_base_group_or_create_one(user)
        login(self.request, user)
        messages.success(self.request, "Вы успешно зарегестрированы!")
        return redirect(self.success_url)


class ProfileDetailView(SingleObjectMixin, ListView):
    """
    Return the user profile by the 'username' slug
    and its published articles list.
    """

    template_name = "users/profile.html"
    context_object_name = "author"
    slug_field = "username"
    slug_url_kwarg = "username"
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        """
        Assigning the desired User object to
        object atrribute for further processing.
        """
        self.object = self.get_object(
            queryset=get_users_with_all_counter(),
        )
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.article_set.all().defer("language_id", "body")


class UserListView(ListView):
    """Rerturn the registred users list."""

    model = get_user_model()
    paginate_by = 5

    def get_queryset(self):
        self.filter = UserFilter(
            self.request.GET,
            queryset=get_users_with_counters(),
            request=self.request,
        )
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter
        return context


@method_decorator(decorator=atomic, name="dispatch")
class UserUpdateView(
    UserPassesTestMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView
):
    """Update User data."""

    permission_required = "users.change_user"

    model = get_user_model()
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/update_user.html"
    form_class = CustomUserChangeForm

    success_message = "Вы успешно обновили свои данные."

    def test_func(self):
        "Verify user identity by session user object"
        return self.request.user.get_username() == self.kwargs.get("username")


@method_decorator(decorator=atomic, name="dispatch")
class UserDestroyView(
    UserPassesTestMixin, PermissionRequiredMixin, SuccessMessageMixin, BaseDeleteView
):
    """Delete user."""

    permission_required = "users.delete_user"

    model = get_user_model()
    slug_field = "username"
    slug_url_kwarg = "username"
    success_url = settings.LOGOUT_REDIRECT_URL

    success_message = "Аккаунт успешно удален"

    def test_func(self):
        "Verify user identity by session user object"
        return self.request.user.get_username() == self.kwargs.get("username")


@method_decorator(decorator=atomic, name="dispatch")
class AddBlogToProfileView(LoginRequiredMixin, SuccessMessageMixin, View):
    """
    Add blog to the list that the current authenticated user is following.
    """

    def post(self, request, *args, **kwargs):
        blog_id = request.POST.get("blog_id")
        blog_name = request.POST.get("blog_name")
        add_blogs_to_user(request.user, blog_id)
        messages.success(request, f"Вы подписались на блог {blog_name}")
        return redirect("blog:articles_by_blog", pk=blog_id)


@method_decorator(decorator=atomic, name="dispatch")
class RemoveBlogFromProfileView(LoginRequiredMixin, View):
    """
    Remove blog from the list that the current authenticated user is following.
    """

    def post(self, request, *args, **kwargs):
        blog_id = request.POST.get("blog_id")
        blog_name = request.POST.get("blog_name")
        remove_blogs_from_user(request.user, blog_id)
        messages.success(request, f"Вы отписались от блога {blog_name}")
        return redirect("blog:articles_by_blog", pk=blog_id)


class UserFollowingListView(LoginRequiredMixin, ListView):
    """Returns a followng list of current user."""

    model = get_user_model()
    paginate_by = 5

    def get_queryset(self):
        self.filter = UserFilter(
            self.request.GET,
            queryset=get_user_following_list(self.request.user),
            request=self.request,
        )
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter
        return context


@method_decorator(decorator=atomic, name="dispatch")
class AddAuthorToProfileView(LoginRequiredMixin, View):
    """
    Add author to the list that the current authenticated user is following.
    """

    def post(self, request, *args, **kwargs):
        author_id = request.POST.get("author_id")
        author_username = request.POST.get("author_username")
        add_authors_to_user(request.user, author_id)
        messages.success(request, f"Вы подписались на {author_username}")
        return redirect("users:profile", username=author_username)


@method_decorator(decorator=atomic, name="dispatch")
class RemoveAuthorFromProfileView(LoginRequiredMixin, View):
    """
    Remove author from the list that the current
    authenticated user is following.
    """

    def post(self, request, *args, **kwargs):
        author_id = request.POST.get("author_id")
        author_username = request.POST.get("author_username")
        remove_authors_from_user(request.user, author_id)
        messages.success(request, f"Вы отписались от {author_username}")
        return redirect("users:profile", username=author_username)

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %} Автор | {{ author.get_username }} {% endblock %}

{% block content %}
<h2 class="display-4">Об авторе</h2>
{% if user.get_username == author.get_username %}
<a href="{% url 'blog:new_article' %}" class="btn btn-outline-secondary mt-1 mb-3  btn-sm">Создать статью</a>
<a href="{% url 'users:update_user' user.get_username %}"
  class="btn btn-outline-secondary mt-1 mb-3  btn-sm">Редактировать</a>
{% endif %}

{% if user.is_authenticated %}
  {% if user.get_username != author.get_username %}
    {% if author not in user.following.all %}
    <form action="{% url 'users:add_author_to_profile' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="author_id" value="{{ author.id }}">
      <input type="hidden" name="author_username" value="{{ author.username }}">
      <button class="btn btn-outline-secondary mb-2">Подписаться</button>
    </form>
    {% else %}
    <form action="{% url 'users:remove_author_from_profile' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="author_id" value="{{ author.id }}">
      <input type="hidden" name="author_username" value="{{ author.username }}">
      <button class="btn btn-outline-secondary mb-2">Отписаться</button>
    </form>
    {% endif %}
  {% endif %}
{% endif %}

<div class="mb-3">
  {% load thumbnail %}
  {% thumbnail author.profile_picture "75x75" crop="center" as im %}
  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-fluid img-thumbnail rounded-pill"
    alt="profile-picture">
  {% empty %}
  {% load static %}
  <img src="{% static 'users/images/default.jpg' %}" width="75" height="75" class="img-fluid img-thumbnail rounded-pill"
    alt="profile-picture">
  {% endthumbnail %}

  <b>{{ author.get_username }}</b> {% if author.is_online %}<span class="text-success">Online</span>{% endif %}
</div>

<div class="mt-2 mb-5">
  {% if not author.is_online %}
  {% if author.last_seen %}
  {% load humanize %}
  <span>Был(-а) в сети: {{ author.last_seen|naturaltime }}</span>
  {% else %}
  <span>Был(-а) в сети: Давно</span>
  {% endif %}
  {% endif %}
</div>

{% if author.get_full_name %}
<p><b>Полностью: </b>{{ author.get_full_name }}</p>
{% endif %}
<p><b>Подписчиков: </b>{{ author.followers__count }}</p>
<p><b>Подписок: </b>{{ author.following__count }}</p>
<p><b>Публикаций: </b>{{ author.article__count }}</p>
{% if author.about_me %}
<p class="about_author"><b>О себе: </b>{{ author.about_me }}</p>
{% endif %}

{% include "blog/includes/articles_snippet.html" with is_users_articles=True %}
{% endblock %}

users/templates/users/update_user.html
{% extends 'base.html' %}

{% block title %}Редактирование профиля | {{ user.get_username }} {% endblock %}

{% block style %}
{{ form.media.css }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}
{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% load bootstrap5 %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary" onclick="this.form.submit(); this.disabled = true;">
    Сохранить
  </button>
  {% endbuttons %}
</form>

<!-- Кнопка-триггер модального окна -->
<button type="button" class="btn btn-danger mt-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Удалить аккаунт
</button>

<!-- Модальное окно -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="RemoveModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Удаление аккаунта</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-body">
        Вы уверены что хотите удалить ваш аккаунт?
        Аккаунт будет удален навсегда.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <form action="{% url 'users:destroy_user' user.get_username %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger" onclick="this.form.submit(); this.disabled = true;">
            Удалить
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

<a href="{% url 'password_change' %}" class="btn btn-secondary mt-2">Изменить пароль</a>
{% endblock %}

users/templates/users/user_list.html
{% extends "base.html" %}

{% block title %}Авторы{% endblock %}

{% load bootstrap5 %}

{% block content %}
<section>
  <h2 class="display-4">Авторы</h2>

  <form method="get">
    <div class="d-flex align-items-start flex-column">
      <div class="d-flex justify-content-start align-items-center">
        <div>{% bootstrap_field filter.form.username bound_css_class='' %}</div>
        <div class="mt-3 ms-2"><input type="submit" class="btn btn-outline-primary" value="Найти"></div>
      </div>
      <div class="d-flex justify-content-start align-items-start">
        <div>{% bootstrap_field filter.form.by_followers_count bound_css_class='form-select-sm' %}</div>
        <div>{% bootstrap_field filter.form.by_article_count bound_css_class='form-select-sm' %}</div>
      </div>
    </div>
  </form>

  <ul class="list-group list-group-flush">
    <li class="list-group-item d-flex justify-content-end align-items-start">
      <div style="font-size: small;">Подписчики</div>
      <div class="ms-2" style="font-size: small;">Публикации</div>
    </li>
    {% for author in user_list %}
    <li class="list-group-item d-flex justify-content-between align-items-start">

      {% load thumbnail %}
      {% thumbnail author.profile_picture "60x60" crop="center" as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
        class="img-fluid img-thumbnail rounded-pill" alt="profile-picture">
      {% empty %}
      {% load static %}
      <img src="{% static 'users/images/default.jpg' %}" width="60" height="60"
        class="img-fluid img-thumbnail rounded-pill" alt="profile-picture">
      {% endthumbnail %}

      <div class="ms-2 mt-1 me-auto text-break">
        <a href="{% url 'users:profile' author.username %}">
          <div class="fw-bold text-break">
            {{ author.username }}
          </div>
        </a>
        {% if author.is_online %}
        <span class="text-success">Онлайн</span>
        {% else %}
        <span class="text-secondary">Не в сети</span>
        {% endif %}
        <div>{{ author.get_full_name }}</div>
        {% if author.about_me %}
        <div>{{ author.about_me }}</div>
        {% endif %}
      </div>
      <span class="badge bg-secondary rounded-pill ms-5 me-2">{{ author.followers__count }}</span>
      <span class="badge bg-secondary rounded-pill ms-5">{{ author.article__count }}</span>
    </li>
    {% empty %}
    <p class="mt-3">Пока ничего нет</p>
    {% endfor %}
  </ul>
</section>
{% endblock %}