blog/urls.py
"""Blog app URL Configuration."""

from django.urls import path
from django.views.generic.base import RedirectView

from blog import views

app_name = "blog"

urlpatterns = [
    path("articles/", views.IndexListView.as_view(), name="index"),
    path("", RedirectView.as_view(pattern_name="blog:index", permanent=False)),
    path("feed/", views.PersonalNewsFeedView.as_view(), name="feed"),
    path("articles/<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("articles/new/", views.ArticleCreateView.as_view(), name="new_article"),
    path("articles/<int:pk>/edit/", views.ArticleUpdateView.as_view(), name="update_article"),
    path("articles/<int:pk>/delete/", views.ArticleDestroyView.as_view(), name="destroy_article",),
    path("blogs/", views.BlogListView.as_view(), name="blogs"),
    path("blogs/<int:pk>/", views.BlogDetailView.as_view(), name="articles_by_blog"),
    path("blogs/new", views.BlogCreateView.as_view(), name="new_blog"),
    path("languages/new", views.LanguageCreateView.as_view(), name="new_language"),
    path("bookmarks/", views.BookmarksView.as_view(), name="bookmarks"),
    path("bookmarks/add", views.AddArticleInBookmarks.as_view(), name="add_article_to_bookmarks"),
    path("bookmarks/delete", views.RemoveArticleFromBookmarks.as_view(), name="remove_article_from_bookmarks"),
]

config/urls.py
"""
Django-blog URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Администрирование Incognito"
admin.site.index_title = "Администрирование вашего сайта"
admin.site.site_title = "Административный сайт Incognito"


urlpatterns = [
    path("", include("blog.urls")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path("select2/", include("django_select2.urls")),
]

urlpatterns += [
    # 'неявные' view из auth app (шаблоны лежат в /templates/registration)
    path("users/", include("django.contrib.auth.urls")),
    # остальные view и шаблоны пользователей лежат в users app
    path("users/", include("users.urls")),
]

urlpatterns += [
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
    path('__debug__/', include('debug_toolbar.urls')),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
"""Users app URL Configuration."""

from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.UserListView.as_view(), name="users"),
    path("register/", views.SiqnUp.as_view(), name="signup"),
    path("<username>", views.ProfileDetailView.as_view(), name="profile"),
    path("<username>/edit", views.UserUpdateView.as_view(), name="update_user"),
    path("<username>/delete", views.UserDestroyView.as_view(), name="destroy_user"),
    path("following/", views.UserFollowingListView.as_view(), name="following"),
    path("add_author/", views.AddAuthorToProfileView.as_view(), name="add_author_to_profile"),
    path("remove_author/", views.RemoveAuthorFromProfileView.as_view(), name="remove_author_from_profile"),
    path("add_blog/", views.AddBlogToProfileView.as_view(), name="add_blog_to_profile"),
    path("remove_blog/", views.RemoveBlogFromProfileView.as_view(), name="remove_blog_from_profile"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% block title %}Главная{% endblock %}</title>
  {% load static %}
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}">

  {# Load the tag library #}
  {% load bootstrap5 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  {% load cache %}

  {% block style %}{% endblock %}
</head>

<body class="d-flex flex-column min-vh-100">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Incognito</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09"
          aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:feed' %}">Моя лента</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link text-dark" aria-current="page" href="{% url 'blog:index' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:users' %}">Авторы</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:blogs' %}">Блоги</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:bookmarks' %}">Закладки</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:profile' user.username %}">Мой профиль</a>
            </li>
            {% endif %}
          </ul>
          <form method="get" action="{% url 'blog:index' %}" class="me-2 mb-2 mb-sm-2 mb-md-2 mt-lg-2">
            <input type="text" value='{{ query }}' name='search_query' placeholder='Найти статью' class='form-control' aria-label='Search'>
          </form>
          {% if user.is_authenticated %}
          <div>
            <a class="btn btn-outline-primary me-2" href="{% url 'logout' %}">Выйти</a>
            {% else %}
            <a class="btn btn-outline-primary me-2" href="{% url 'users:signup' %}">Регистрация</a>
            <a class="btn btn-outline-primary me-2" href="{% url 'login' %}?next={{request.path}}">Вход</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

  {# Display django.contrib.messages as Bootstrap alerts #}
  {% bootstrap_messages %}

  <main class="container mt-2 mb-5">
    {% block content %}{% endblock %}

    {% block pagination %}
    {% if is_paginated %}
    {% load url_replacer %}
    <nav aria-label="Search results pages" class="mt-4">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link"
            href="?{% replace_param page=page_obj.previous_page_number %}">Предыдущая</a></li>
        <li class="page-item">
          <a class="page-link" href="?{% replace_param page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="">Предыдущая</a></li>
        {% endif %}

        <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% replace_param page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        </li>
        <li class="page-item"><a class="page-link"
            href="?{% replace_param page=page_obj.next_page_number %}">Следующая</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="">Следующая</a></li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    {% endblock %}
  </main>
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top mt-auto">
    <div class="col-md-4 d-flex align-items-center ms-3">
      <span class="text-muted ms-3">© 2023 Incognito, Inc</span>
    </div>

    <ul class="nav col-md-4 col-12  justify-content-center list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="https://www.linkedin.com/in/mikhailfed68/" target="_blank">
        <img src="{% static 'social/linkedin.png' %}" alt="linkedin" width="24" height="24">
      </a></li>
      <li class="ms-3"><a class="text-muted" href="https://github.com/mikhailfed68" target="_blank">
        <img src="{% static 'social/github.png' %}" alt="github" width="24" height="24">
      </a></li>
      <li class="ms-3"><a class="text-muted" href="https://t.me/mikhailfed007" target="_blank">
        <img src="{% static 'social/telegram.png' %}" alt="telegram" width="24" height="24">
      </a></li>
      <li class="ms-3"><a class="text-muted" href="https://vk.com/id502731933" target="_blank">
        <img src="{% static 'social/vk.png' %}" alt="vk" width="24" height="24">
      </a></li>
      <li class="ms-3 me-5"><a class="text-muted" href="https://instagram.com/mikhailfedoroov" target="_blank">
        <img src="{% static 'social/instagram.png' %}" alt="instagram" width="24" height="24">
      </a></li>
    </ul>
  </footer>
</body>

</html>